# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/gitleaks/gitleaks #security check
    rev: v8.29.0
    hooks:
      - id: gitleaks
        name: "gitleaks security check"
  - repo: https://github.com/astral-sh/uv-pre-commit #update uv lock file
    rev: 0.9.9
    hooks:
      - id: uv-lock
  - repo: https://github.com/tsvikas/sync-with-uv #sync uv tools and pre commit tools
    rev: v0.4.0 # replace with the latest version
    hooks:
      - id: sync-with-uv
  - repo: https://github.com/astral-sh/ruff-pre-commit #use ruff to format and lint python
    # Ruff version.
    rev: v0.14.5
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/DavidAnson/markdownlint-cli2 #format and lint markdown
    rev: v0.19.0
    hooks:
      - id: markdownlint-cli2 #format
        args: [--fix]
      - id: markdownlint-cli2 #lint
