project:
  type: website
  render:
    - "*.qmd"
  post-render: quartoScripts/restoreMarkdownToRepositoryHierachy.sh

website:
  title: "Beginning to Code with Python: Notes, Examples and Exercises"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Programming Fundamentals"
        contents:
          - 01_ProgrammingFundamentals/02_PythonAndProgramming/Chapter_02.qmd
          - 01_ProgrammingFundamentals/03_PythonProgramStructure/Chapter_03.qmd
          - 01_ProgrammingFundamentals/04_WorkingWithVariables/Chapter_04.qmd
format:
  html:
    toc: true
    toc-depth: 6
    code-fold: false
    code-links: repo
  gfm:
    toc: true
    toc-depth: 6
    filters:
      - quartoScripts/remove_ansi.lua
execute:
  enabled: true
  error: true
engine: jupyter
