project:
  type: website
  render:
    - "*.qmd"
  post-render: quartoScripts/restoreMarkdownToRepositoryHierachy.sh

website:
  title: "Beginning to Code with Python: Notes, Examples and Exercises"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Programming Fundamentals"
        contents:
          - 01_ProgrammingFundamentals/02_PythonAndProgramming/Chapter_02.qmd
          - 01_ProgrammingFundamentals/03_PythonProgramStructure/Chapter_03.qmd
          - 01_ProgrammingFundamentals/04_WorkingWithVariables/Chapter_04.qmd
          - 01_ProgrammingFundamentals/05_MakingDecisions/Chapter_05.qmd
          - 01_ProgrammingFundamentals/06_RepeatingActionsWithLoops/Chapter_06.qmd
          - 01_ProgrammingFundamentals/07_UsingFunctions/Chapter_07.qmd
          - 01_ProgrammingFundamentals/08_StoringCollectionsOfData/Chapter_08.qmd
      - section: "Advanced Programming"
        contents:
          - section: 02_AdvancedProgramming/09_UsingClasses/Chapter_09.qmd
            contents:
              - 02_AdvancedProgramming/09_UsingClasses/Chapter_09_ExtensionExercises.qmd
          - 02_AdvancedProgramming/10_UseClassesToCreateActiveObjects/Chapter_10.qmd
          - 02_AdvancedProgramming/11_ObjectBasedSolutionDesign/Chpater_11.qmd
format:
  bookup-html:
    code-fold: false
    code-links: repo
  gfm:
    filters:
      - quartoScripts/remove_ansi.lua
toc: true
toc-depth: 6
format-links: false
execute:
  enabled: true
  error: true
engine: jupyter
